-
  name: oneTwoTen
  animation: line
  minSum: 1
  maxSum: 10
  subLevels:
  -
    range:
      start: 0
      end: 4
    operations:
      -
        operator: '+'
        start: 1
        end: 2
  -
    range:
      start: 5
      end: 9
    operations:
      -
        operator: '+'
        start: 1
        end: 2
-
  name: oneTwoTenMinus
  animation: line
  minSum: 1
  maxSum: 10
  subLevels:
  -
    range:
      start: 1
      end: 5
    operations:
      -
        operator: '-'
        start: 1
        end: 2
  -
    range:
      start: 6
      end: 10
    operations:
      -
        operator: '-'
        start: 1
        end: 2